=begin
#Swagger Petstore

#:dog: :cat: :rabbit: This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YandexDirectClient::ClientNotificationRestrictions
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientNotificationRestrictions' do
  before do
    # run before each test
    @instance = YandexDirectClient::ClientNotificationRestrictions.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientNotificationRestrictions' do
    it 'should create an instance of ClientNotificationRestrictions' do
      expect(@instance).to be_instance_of(YandexDirectClient::ClientNotificationRestrictions)
    end
  end
  describe 'test attribute "element"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CAMPAIGNS_TOTAL_PER_CLIENT", "CAMPAIGNS_UNARCHIVED_PER_CLIENT", "ADGROUPS_TOTAL_PER_CAMPAIGN", "ADS_TOTAL_PER_ADGROUP", "KEYWORDS_TOTAL_PER_ADGROUP", "AD_EXTENSIONS_TOTAL", "STAT_REPORTS_TOTAL_IN_QUEUE", "FORECAST_REPORTS_TOTAL_IN_QUEUE", "WORDSTAT_REPORTS_TOTAL_IN_QUEUE", "API_POINTS", "GENERAL_DOMAIN_BLACKLIST_SIZE", "VIDEO_DOMAIN_BLACKLIST_SIZE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.element = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
