=begin
#Swagger Petstore

#:dog: :cat: :rabbit: This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 1.0.0
Contact: apiteam@swagger.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for YandexDirectClient::ClientGetItemRequestParams
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientGetItemRequestParams' do
  before do
    # run before each test
    @instance = YandexDirectClient::ClientGetItemRequestParams.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientGetItemRequestParams' do
    it 'should create an instance of ClientGetItemRequestParams' do
      expect(@instance).to be_instance_of(YandexDirectClient::ClientGetItemRequestParams)
    end
  end
  describe 'test attribute "selection_criteria"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_names"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["AccountQuality", "Archived", "ClientId", "ClientInfo", "CountryId", "CreatedAt", "Currency", "Grants", "Bonuses", "Login", "Notification", "OverdraftSumAvailable", "Phone", "Representatives", "Restrictions", "Settings", "Type", "VatRate"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.field_names = value }.not_to raise_error
      # end
    end
  end

end
